name: lazy_memo

description: Helper classes for defining lazy variables and memoized functions.

version: 0.1.2

homepage: https://github.com/simphotonics/lazy_memo

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies: null

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
